content changed

diff --git a/docker/prod/Dockerfile b/docker/prod/Dockerfile
--- a/docker/prod/Dockerfile
+++ b/docker/prod/Dockerfile
@@ -8,13 +8,15 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* bun.lockb*  ./
 
-RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f bun.lockb ]; then bun install --frozen-lockfile; \
-    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+# RUN \
+#     if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#     elif [ -f package-lock.json ]; then npm ci; \
+#     elif [ -f bun.lockb ]; then bun install --frozen-lockfile; \
+#     elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+#     else echo "Lockfile not found." && exit 1; \
+#     fi
+
+RUN bun install --frozen-lockfile
 
 # 2. Rebuild the source code only when needed
 FROM base AS builder
